version: '3.8'

services:
  frontend:
    build: ./app
    volumes:
      - ./app:/app  
      - /app/node_modules 
    ports:
      - "5173:5173" 
    command: ["npm", "run", "dev"] 

  backend:
    build: ./api
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app  
      - /app/node_modules 
    ports:
      - "3000:3000" 
    command: ["npm", "run", "start:dev"]
