version: '3.8'

services:
  frontend:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./app/.env
    volumes:
      - ./app/dist:/usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]

  backend:
    build: ./api
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env
    volumes:
      - /app/node_modules
    command: ["npm", "run", "start"]
